domainic-attributer/CHANGELOG.md
domainic-attributer/README.md
rbs_collection.lock.yaml

The README now explicitly documents that Domainic::Attributer's constraints (type validation, coercion, nullability checks, etc.) are enforced throughout an object's entire lifecycle, not just during initialization.
Key changes:
- Added new "Attribute Constraints and Lifecycle" section with clear examples
- Enhanced type validation examples to show both init and setter validation
- Updated coercion examples to demonstrate consistent behavior
- Added more examples showing constraint enforcement during assignment
This addresses issue #10 where users might incorrectly assume constraints only apply during object creation.
resolves #10

Update Attributer README and CHANGELOG

---

Gemfile.lock
domainic-attributer/CHANGELOG.md
domainic-attributer/README.md
domainic-attributer/domainic-attributer.gemspec
domainic-attributer/lib/domainic/attributer/attribute.rb
domainic-attributer/lib/domainic/attributer/attribute/coercer.rb
domainic-attributer/lib/domainic/attributer/attribute/validator.rb
domainic-attributer/sig/domainic/attributer/attribute/coercer.rbs
domainic.gemspec
rbs_collection.lock.yaml

This improves how Domainic::Attributer handles nil values during attribute coercion. Currently, developers must manually handle nil values in coercion handlers, which leads to repetitive boilerplate code and potential inconsistencies in nil handling across attributes.
The solution implements a two-part approach:
1. Prevent coercion attempts on nil values for non-nilable attributes
2. Update documentation to clearly explain the behavior and best practices
Key Changes:
- Move responsibility for nil and Undefined value handling from Attribute to Coercer
- Skip coercion attempts when a value is nil and the attribute is not nilable
- Update documentation with comprehensive guidance for handling nilable vs non-nilable attributes
- Bump version to 0.2.0 to reflect breaking change in coercer …

Improve nil handling in coercer and bump version to 0.2.0

---

.mdl.rb
README.md
domainic-attributer/README.md

This PR improves the documentation around our DSL methods and their aliases. The key changes:
- Added a comprehensive "Defining Attributes" section showing both option hash and block syntax
- Organized all available configuration options by category (validation, coercion, etc.)
- Documented all method aliases so users can choose names that fit their style
- Added collapsible sections to improve README readability
- Standardized code examples to use single quotes per rubocop style
Our documentation didn't clearly show all the available method aliases (like `not_null` vs `non_nilable`). This led to confusion about naming options and duplicate feature requests for aliases that already existed.
- Added detailed documentation of all DSL methods and their aliases
- Organized methods by category …

Document DSL method aliases and options

---

domainic-attributer/lib/domainic/attributer/attribute/validator.rb
domainic-attributer/sig/domainic/attributer/attribute/validator.rbs

This fixes a bug introduced in #18 that would produce a confusing stack trace on validation failure.  This ensures that a single ArgumentError is raised when validation fails while maintaining the intended functionality of ValidationExecutionErrors.
Changelog:
- fixed #18 Duplicate Validation Errors Raised on Invalid Attribute Values
- removed `Domainic::Attributer::Validation::ValidationFailure`

Fix Duplicate Validation Errors Raised on Invalid Attribute Values

---

README.md
rbs_collection.lock.yaml

This fixes a broken link to domainic-attributer in the main README.md file.
fixes #63

Fix broken link in README

---

domainic-type/lib/domainic/type/behavior/enumerable_behavior.rb
domainic-type/lib/domainic/type/constraint/behavior.rb
domainic-type/lib/domainic/type/constraint/constraints/inclusion_constraint.rb
domainic-type/sig/domainic/type/constraint/constraints/inclusion_constraint.rbs
domainic-type/spec/domainic/type/constraint/inclusion_constraint_spec.rb

Refines the InclusionConstraint's error reporting to only show values that failed the inclusion test rather than all values. This makes the error messages more precise and useful by showing exactly which expected values were missing from the collection.
For example, given a type expecting values "a", "b", and "c", if "c" is the only missing value, the error now shows:
Expected Array(including "a", "b" and "c"), but got Array(excluding "c")
Instead of the previous:
Expected Array(including "a", "b" and "c"), but got Array(excluding "a", "b" and "c")
Key changes:
- Filter expected values in short_violation_description to show only missing ones
- Add tests for various missing value scenarios
- Update documentation with examples of the new behavior
- Add test coverage for edge cases like …

Refactor `Domainic::Type::Constraint::InclusionConstraint`

---

domainic-type/lib/domainic/type/constraint/constraints/and_constraint.rb
domainic-type/lib/domainic/type/constraint/constraints/not_constraint.rb
domainic-type/lib/domainic/type/types/anything_type.rb
domainic-type/sig/domainic/type/constraint/constraints/and_constraint.rbs
domainic-type/sig/domainic/type/types/anything_type.rbs
domainic-type/spec/domainic/type/anything_type_spec.rb
domainic-type/spec/domainic/type/constraint/and_constraint_spec.rb
domainic-type/spec/domainic/type/constraint/not_constraint_spec.rb

This commit introduces a new `AnythingType` that validates successfully for all values except explicitly excluded ones. Additionally, it refines error messaging in the `AndConstraint` and `NotConstraint` classes to improve clarity.
Changelog:
- added `Domainic::Type::AnythingType`
- changed `Domainic::Type::Constraint::NotConstraint` to no longer prefix violation messages with "not"
- changed `Domainic::Type::Constraint::AndConstraint` to only use "and" before the final expectation
- fixed `Domainic::Type::Constraint::AndConstraint` to accept a single constraint as an argument for `#expecting`
resolves #59

Add `Domainic::Type::AnythingType`

---

domainic-type/lib/domainic/type/constraint/constraints/method_presence_constraint.rb
domainic-type/lib/domainic/type/types/anything_type.rb
domainic-type/lib/domainic/type/types/duck_type.rb
domainic-type/sig/domainic/type/constraint/constraints/method_presence_constraint.rbs
domainic-type/sig/domainic/type/types/anything_type.rbs
domainic-type/sig/domainic/type/types/duck_type.rbs
domainic-type/spec/domainic/type/constraint/method_presence_constraint_spec.rb
domainic-type/spec/domainic/type/duck_type_spec.rb

This adds support for duck typing validation by introducing two new components:
1. `MethodPresenceConstraint` - A base constraint that validates whether an object responds to a specified method
2. `DuckType` - A type that validates objects based on their method interface, supporting both required and excluded methods
Example usage:
```ruby
type = Domainic::Type::DuckType.responding_to(:foo).not_responding_to(:bar)
obj1 = Struct.new(:foo).new('foo')
type.validate(obj1) #=> true  # has :foo but not :bar
obj2 = Struct.new(:foo, :bar).new('foo', 'bar') 
type.validate(obj2) #=> false  # has :bar which is excluded
obj3 = Struct.new(:baz).new('baz')
type.validate(obj3) #=> false  # missing required :foo
```
This implements flexible type validation based on method presence rather than class …

Add `Domainic::Type::DuckType` and related constraints

---

domainic-type/lib/domainic/type/behavior.rb
domainic-type/lib/domainic/type/constraint/behavior.rb
domainic-type/lib/domainic/type/constraint/set.rb
domainic-type/sig/domainic/type/behavior.rbs
domainic-type/sig/domainic/type/constraint/behavior.rbs
domainic-type/sig/domainic/type/constraint/set.rbs
domainic-type/spec/domainic/type/constraint/behavior_spec.rb

Added support for type-provided coercion procs in constraints while maintaining the existing constraint-level coercion system. This allows types to provide custom coercion logic that runs after the constraint's own coercion but before validation.
Key changes:
- Added coerce_actual_for_type method to handle type coercion
- Integrated type coercion into the constraint validation pipeline
- Added full test coverage for type coercion scenarios
- Updated documentation with new coercion details
Type coercion runs after constraint coercion but before validation, enabling a clean separation of concerns while maintaining composability. Failures in type coercion cause validation to fail gracefully.
Changelog:
- changed `Constraint::Behavior#satisfied?` to use type coercion
resolves #83

Add type-level coercion support to constraints

---

Gemfile.lock
rbs_collection.lock.yaml

This bumps a few dependencies and updates the rbs collection
* bumps json from 2.9.0 -> 2.9.1
* bumps logger from 1.6.3 -> 1.6.4
* bumps thor signatures to new revision

Bump dependencies

---

.rubocop.yml
Gemfile
Gemfile.lock
domainic-attributer/lib/domainic/attributer/class_methods.rb
domainic-attributer/sig/domainic/attributer/class_methods.rbs
domainic-attributer/spec/domainic/attributer/attribute_spec.rb
domainic-attributer/spec/domainic/attributer/dsl/initializer_spec.rb
domainic-dev/lib/domainic/dev/cli/command/lint_markdown_command.rb
domainic-dev/lib/domainic/dev/gem.rb
domainic-dev/lib/domainic/dev/generator/gem_generator.rb
domainic-dev/sig/domainic/dev/cli/command/lint_markdown_command.rbs
domainic-dev/sig/domainic/dev/gem.rbs
domainic-dev/sig/domainic/dev/generator/gem_generator.rbs
domainic-type/lib/domainic/type/behavior/enumerable_behavior.rb
domainic-type/lib/domainic/type/constraint/resolver.rb
domainic-type/lib/domainic/type/types/specification/duck_type.rb
domainic-type/sig/domainic/type/behavior/enumerable_behavior.rbs
domainic-type/sig/domainic/type/constraint/resolver.rbs
domainic-type/sig/domainic/type/types/specification/duck_type.rbs
domainic-type/spec/domainic/type/constraint/all_constraint_spec.rb
domainic-type/spec/domainic/type/constraint/and_constraint_spec.rb
domainic-type/spec/domainic/type/constraint/any_constraint_spec.rb
domainic-type/spec/domainic/type/constraint/behavior_spec.rb
domainic-type/spec/domainic/type/constraint/not_constraint_spec.rb
domainic-type/spec/domainic/type/constraint/or_constraint_spec.rb

Adds the rubocop-ordered_methods extension to enforce alphabetical ordering of methods within visibility groups (public, protected, private). Ran auto-correction across the codebase to align with this standard.
* Added rubocop-ordered_methods to development dependencies
* Added extension to .rubocop.yml configuration
* Auto-corrected method ordering in 18 files
This change standardizes method organization throughout the project, improving code readability and maintainability.

Add `rubocop-ordered_methods` and fix method ordering

---

domainic-attributer/CHANGELOG.md
domainic-attributer/lib/domainic/attributer/attribute/mixin/belongs_to_attribute.rb
domainic-attributer/lib/domainic/attributer/dsl/attribute_builder/option_parser.rb
domainic-attributer/lib/domainic/attributer/dsl/initializer.rb

Fix missing require statements needed for proper class loading:
- require 'undefined' in option_parser.rb and initializer.rb
- require 'attribute' in belongs_to_attribute.rb
These dependencies were previously working through Ruby's autoload but should be explicitly required for clearer code organization and to prevent potential loading issues.
- fixed `Domainic::Attributer::DSL::OptionParser` missing require for `Domainic::Attributer::Undefined`
- fixed `Domainic::Attributer::DSL::Initializer` missing require for `Domainic::Attributer::Undefined`
- fixed `Domainic::Attributer::Attribute::BelongsToAttribute` missing require for `Domainic::Attributer::Attribute`

Fix missing require statements in Attributer

---

.github/actions/test/ruby/action.yml
.github/workflows/build.yml
.markdownlint.yml
.mdl.rb
Gemfile
Gemfile.lock
README.md
spec/spec_helper.rb

Integrates Codacy for code coverage tracking and improves documentation linting configuration. Consolidates markdown linting rules into a single configuration file and sets up coverage reporting through simplecov-lcov.
* Added .markdownlint.yml for centralized markdown linting rules
* Modified .mdl.rb to read from .markdownlint.yml
* Added simplecov-lcov gem for LCOV coverage reporting
* Configured SimpleCov to use LCOV formatter
* Added Codacy badges to main README.md
* Excluded domainic-dev from coverage metrics
* Updated test workflow to report coverage to Codacy

Add Codacy code coverage reporting and documentation linting

---

domainic-type/lib/domainic/type/behavior.rb
domainic-type/lib/domainic/type/behavior/enumerable_behavior.rb
domainic-type/lib/domainic/type/behavior/range_builder.rb
domainic-type/lib/domainic/type/constraint/constraints/structural/range_constraint.rb
domainic-type/sig/domainic/type/behavior.rbs
domainic-type/sig/domainic/type/behavior/enumerable_behavior.rbs
domainic-type/sig/domainic/type/behavior/range_builder.rbs
domainic-type/sig/domainic/type/constraint/constraints/structural/range_constraint.rbs
domainic-type/spec/domainic/type/behavior/range_builder_spec.rb

This update introduces more expressive and flexible size constraints in the `EnumerableBehavior` module. Key changes include:
1. **RangeBuilder Class**  
- Provides a fluent interface for size constraints.
- Supports methods like `at_least`, `at_most`, `between`, and `exactly`.
- Enables method chaining, integrating with the parent type system.
- Includes full documentation and specs.
- Reusable for numerics and strings.
2. **Enhanced `having_count` Method**  
- Supports both builder pattern and direct options:
- Fluent API: `having_count.at_least(5).at_most(10)`
- Direct options: `having_count(between: { min: 5, max: 10 })`
3. **Inclusive Option for `RangeConstraint`**  
- Adds support for exclusive ranges via `having_count.between`.
- Defaults to inclusive behavior for backward …

Enhance Enumerable module with fluent range constraints

---

.github/COMMIT_MESSAGE_TEMPLATE.md
bin/setup

This change automates two development workflow improvements:
1. Sets up a standardized git commit message template
2. Adds a pre-commit hook that runs CI checks before commits
Changes made:
- Added git commit template configuration to bin/setup
- Added pre-commit hook creation to bin/setup that runs bin/dev ci
- Created .github/gitmessage template file
The commit template helps maintain consistent commit messages while the pre-commit hook ensures code quality by running CI checks locally before commits are made.
resolves #100

Add git commit template and pre-commit hook setup

---

domainic-dev/lib/domainic/dev/cli/command/base_command.rb
domainic-dev/lib/domainic/dev/cli/command/lint_markdown_command.rb
domainic-dev/sig/domainic/dev/cli/command/base_command.rbs
domainic-dev/sig/domainic/dev/cli/command/lint_markdown_command.rbs

This fixes the ordering of mdl violations in the `bin/dev lint md` output. Additionally, this enhances the output of the violations to link to the appropriate file and line number; as well as link to the mdl rule being violated.  Simply click the line number or mdl rule id, and you will be brought to the appropriate place.
- fixes #97
- mdl violations are now output in line order
- the line numbers of each mdl violation will go directly to the offending file and line number when clicked
- the mdl rule ids of each mdl violation will go directly to the documentation for that rule when clicked.

Fixes `Domainic::Dev::CLI::Command::LintMarkdownCommand`

---

.github/COMMIT_MESSAGE_TEMPLATE.md
docs/milestones/domainic-attributer-v0.1.0.md
docs/milestones/domainic-attributer-v0.2.0.md
docs/milestones/domainic-boundary-v0.1.0.md
docs/milestones/domainic-command-v0.1.0.md
docs/milestones/domainic-type-v0.1.0.md
docs/projects/domainic-v0.1.0/README.md
docs/projects/domainic-v0.1.0/updates/2024-12-12-01.md
docs/projects/domainic-v0.1.0/updates/2024-12-12-02.md

Create a dedicated docs folder to provide a centralized, maintainable location for project and milestone documentation that was previously scattered across GitHub UI elements (project descriptions, milestone descriptions, etc.).
This change improves documentation accessibility and maintainability by:
* Moving documentation from GitHub UI into versioned repository
* Creating a clear organization for projects and milestones
* Enabling proper formatting and structure
* Making documentation available offline
* Simplifying review and maintenance processes
Structure:
* docs/projects/*       Project documentation and updates
* docs/milestones/*     Milestone planning and completion docs
GitHub project and milestone descriptions will now link to these docs rather than duplicating content, …

Add documentation structure for projects and milestones

---

.markdownlint.yml
.rubocop-base.yml
.rubocop-codacy.yml
.rubocop.yml

This breaks our rubocop configuration into environment specific files to attempt to resolve compatibility issues with some of the rubocop extensions we use and codacy.
error from Codacy:
```markdown
An error occurred during this step. Please retry your analysis or contact support.
KubernetesDockerRunner: Container for codacy/codacy-rubocop:5.4.181 exited with non-zero code 1
Error executing the tool
java.lang.Exception: 
Rubocop exited with code 2
stdout: 
stderr: cannot load such file -- rubocop-on-rbs
/usr/local/bundle/gems/rubocop-1.68.0/lib/rubocop/feature_loader.rb:46:in `rescue in rescue in load'
```
* added .rubocop-base.yml
* added .rubocop-codacy.yml
* changed .rubocop.yml to inherit from .rubocop-base.yml
This may not work, I won't know …

Add environment specific rubocop configurations

---

domainic-dev/lib/domainic/dev/cli/generate_cli.rb
domainic-dev/lib/domainic/dev/generator/milestone_doc_generator.rb
domainic-dev/lib/domainic/dev/generator/project_doc_generator.rb
domainic-dev/lib/domainic/dev/generator/project_update_doc_generator.rb
domainic-dev/lib/domainic/dev/generator/templates/milestone_doc/milestone.md.erb
domainic-dev/lib/domainic/dev/generator/templates/project_doc/README.md.erb
domainic-dev/lib/domainic/dev/generator/templates/project_update_doc/update.md.erb
domainic-dev/sig/domainic/dev/generator/milestone_doc_generator.rbs
domainic-dev/sig/domainic/dev/generator/project_doc_generator.rbs
domainic-dev/sig/domainic/dev/generator/project_update_doc_generator.rbs

This adds generators to domainic-dev that automate the generation of project and milestone documentation. This includes
* `bin/dev g project_doc <PROJECT_NAME> <PROJECT_GITHUB_ID>`
* `bin/dev g project_update_doc <PROJECT_NAME>`
* `bin/dev g milestone_doc <MILESTONE_NAME> <MILESTONE_GITHUB_ID> [options]`
resolves #113 
resolves #114 
resolves #115 
resolves #116
* added `Domainic::Dev::Generator::MilestoneDocGenerator`
* added `Domainic::Dev::Generator::ProjectDocGenerator`
* added `Domainic::Dev::Generator::ProjectUpdateDocGenerator`

Add project/milestone documentation generators

---

domainic-type/lib/domainic/type/definitions.rb
domainic-type/sig/domainic/type/definitions.rbs
domainic-type/spec/domainic/type/definitions_spec.rb

Introduces a possibly temporary module providing factory methods for type creation in the Domainic::Type system. This module serves as an initial access point for the type system while the final API is being developed.
Key additions:
* Factory methods for all core types (Array, Hash, String, etc.)
* Nilable variants for common types (String?, Array?, etc.)
* Union type helpers (_Boolean, _Nilable, _Union)
* Duck typing support (_Duck, _Interface)
* Enum/literal type support (_Enum, _Literal)
This implementation is marked as temporary and may undergo significant changes or removal before the final release. It should not be considered part of the stable API at this point.
Changelog:
* added `Domainic::Type::Definitions`

Add `Domainic::Type::Definitions`

---

README.md
docs/experiments/README.md
docs/experiments/domainic-type-alpha-3/CHANGELOG.md
docs/experiments/domainic-type-alpha-3/EXAMPLES.md
docs/experiments/domainic-type-alpha-3/KNOWN_ISSUES.md
docs/experiments/domainic-type-alpha-3/README.md
docs/experiments/domainic-type-alpha-3/TROUBLESHOOTING.md
docs/projects/README.md
docs/projects/domainic-v0.1.0/updates/2024-12-23-01.md

Add comprehensive documentation for the Domainic::Type alpha 3 experiment including:
* Main experiments README explaining purpose and structure
* Domainic::Type experiment docs:
* README.md with quick start, test areas, feedback guidelines
* EXAMPLES.md with basic to advanced usage patterns
* TROUBLESHOOTING.md covering common issues and gotchas
* CHANGELOG.md for tracking experiment versions
* KNOWN_ISSUES.md template for tracking discovered issues
Key additions:
* Clear test focus areas (error messages, types, constraints)
* Detailed examples for all types and constraints
* Issue templates for collecting feedback
* Documentation of mutual constraint overrides
* Version scheme for experiments
see #131

Add documentation for Domainic::Type alpha 3 experiment

---

domainic-type/lib/domainic/type/constraint/set.rb
domainic-type/spec/domainic/type/constraint/set_spec.rb

Modified violation_description method in Set class to only include descriptions from constraints that failed validation. This creates more focused and clearer error messages by excluding status of constraints that passed.
Added comprehensive specs to verify:
* Only failed constraint descriptions are included
* Empty string returned when all constraints pass
* All violation descriptions included when all constraints fail
Changed:
* changed `Domainic::Type::Constraint::Set#violation_description`
fixes #138

Fix `Domainic::Type::Constraint::Set#violation_description`

---

Gemfile.lock
docs/README.md
docs/SECURITY.md
docs/experiments/domainic-type-alpha-3/CHANGELOG.md
docs/experiments/domainic-type-alpha-3/EXAMPLES.md
domainic-type/domainic-type.gemspec
rbs_collection.lock.yaml

This release introduces instance type validation capabilities with the new`Domainic::Type::InstanceType` class and associated constraints. It provides powerful features for validating objects against specific classes, modules, and attribute structures.
Key changes:
* Added `Domainic::Type::InstanceType` for constraining objects to specific classes/modules and validating attributes
* Introduced `_Instance` and `_Instance?` methods in `Domainic::Type::Definitions` for creating instance type constraints
* Added `InstanceOfConstraint` for precise instance type checking
* Added `AttributePresenceConstraint` for validating object attribute presence and typing
* Enhanced documentation with details and usage examples for `InstanceType`
Changelog:
* added …

Release Domainic::Type v0.1.0-alpha.3.0.2

---

domainic-type/lib/domainic/type/behavior.rb
domainic-type/lib/domainic/type/types/core/array_type.rb
domainic-type/lib/domainic/type/types/core/float_type.rb
domainic-type/lib/domainic/type/types/core/hash_type.rb
domainic-type/lib/domainic/type/types/core/integer_type.rb
domainic-type/lib/domainic/type/types/core/string_type.rb
domainic-type/lib/domainic/type/types/core/symbol_type.rb
domainic-type/sig/domainic/type/behavior.rbs
domainic-type/spec/domainic/type/behavior/enumerable_behavior_spec.rb
domainic-type/spec/domainic/type/behavior/numeric_behavior_spec.rb
domainic-type/spec/domainic/type/behavior/string_behavior_spec.rb

Deprecates `Behavior.intrinsic` in favor of the more descriptive `intrinsically_constrain` method name. This change improves code readability by better communicating the method's purpose of defining intrinsic constraints for a type.
* Added deprecation warning to existing `intrinsic` method
* Added new `intrinsically_constrain` method
* Updated all core type definitions to use new method name
* Updated behavior specs to use new method name
* Deprecation includes helpful warning message with call location for debugging
* No functional changes, only method renaming

Rename `intrinsic` to `intrinsically_constrain` with deprecation

---

domainic-type/lib/domainic/type/config/registry.yml
domainic-type/lib/domainic/type/definitions.rb
domainic-type/lib/domainic/type/types/identifier/cuid_type.rb
domainic-type/lib/domainic/type/types/identifier/uuid_type.rb
domainic-type/sig/domainic/type/definitions.rbs
domainic-type/sig/domainic/type/types/identifier/cuid_type.rbs
domainic-type/sig/domainic/type/types/identifier/uuid_type.rbs
domainic-type/spec/domainic/type/cuid_type_spec.rb
domainic-type/spec/domainic/type/definitions_spec.rb
domainic-type/spec/domainic/type/uuid_type_spec.rb

This introduces comprehensive identifier type validation for UUIDs and CUIDs, along with helper methods in `Domainic::Type::Definitions`. The implementation follows RFC 4122 for UUIDs and the official CUID spec, providing robust validation for both standard and specialized formats.
* Added `UUIDType` with support for:
- RFC 4122 compliant validation
- All UUID versions (1-7)
- Both standard and compact formats
- Version-specific constraints
* Added `CUIDType` with support for:
- CUID v1 (25 chars, c-prefix)
- CUID v2 (14-24 chars, k-p prefix)
- Version-specific validation
* Added Definition helpers:
- `_UUID` and `_UUID?` for UUID validation
- `_CUID` and `_CUID?` for CUID validation
- `_ID` and `_ID?` for unified identifier validation (Integer|UUID|CUID)
- Appropriate RBS definitions and …

Add UUIDType and CUIDType with Definition Helpers

---

Gemfile.lock
docs/README.md
docs/SECURITY.md
docs/experiments/domainic-type-alpha-3/CHANGELOG.md
docs/experiments/domainic-type-alpha-3/EXAMPLES.md
docs/experiments/domainic-type-alpha-3/README.md
domainic-type/domainic-type.gemspec
rbs_collection.lock.yaml

This release continues our experiment with flexible type validation in Ruby! 
We're adding network and identifier types to help validate common data 
formats, while also improving API clarity by shifting toward more explicit 
method names.
- Network types:
- EmailAddress - RFC 5321/5322 compliant email validation
- Hostname - RFC 1034/1123 compliant domain validation  
- URI - RFC 3986 compliant URI/URL validation
- Identifier types:
- CUID - Collision-resistant identifier validation
- UUID - RFC 4122 UUID validation with version support
- ID - Combined integer/UUID/CUID validation
- Deprecated `Behavior.intrinsic` in favor of the more explicit `Behavior.intrinsically_constrain`
The full documentation has been updated at https://github.com/domainic/domainic/blob/domainic-type-v0.1.0-alpha. …

Release domainic-type v0.1.0-alpha.3.1.0

---

docs/experiments/domainic-type-alpha-3/CHANGELOG.md
docs/experiments/domainic-type-alpha-3/EXAMPLES.md
docs/experiments/domainic-type-alpha-3/README.md
domainic-type/lib/domainic/type/definitions.rb
domainic-type/sig/domainic/type/definitions.rbs
domainic-type/spec/domainic/type/definitions_spec.rb

Renames the URI type definition method from `_Uri` to `_URI` to follow
Ruby conventions for acronym casing. Maintains backward compatibility
by keeping `_Uri` as an alias.
This change aligns the implementation with our documentation and
matches Ruby conventions where URI (Uniform Resource Identifier) should
be capitalized as an acronym.
fixes #152
* renamed `Domainic::Type::Definitions#_Uri` to `#_URI`
* Fix typo in _CUID aliases ("know" -> "known")
* Update URI type documentation to reflect new URI/URL acronym casing
* Remove emoji from README section header for consistency

Rename _Uri to _URI for proper acronym casing

---

docs/experiments/domainic-type-alpha-3/CHANGELOG.md
domainic-type/lib/domainic/type/types/identifier/cuid_type.rb
domainic-type/lib/domainic/type/types/identifier/uuid_type.rb
domainic-type/lib/domainic/type/types/network/email_address_type.rb
domainic-type/lib/domainic/type/types/network/hostname_type.rb
domainic-type/lib/domainic/type/types/network/uri_type.rb
domainic-type/lib/domainic/type/types/specialized/instance_type.rb

This ensures identifier and network types abort on failure when given the wrong type (i.e. EmailAddressType should abort on failure if it is given anything other than a String)
Specific changes include:
* Applied abort_on_failure: true for String type constraints in:
* CUIDType
* UUIDType
* EmailAddressType
* HostnameType
* URIType
* Updated InstanceType to enforce abort_on_failure: true in the of method for instance validation.
Changelog:
* fixed CUIDType to use abort_on_failure in intrinsic :type constraint
* fixed UUIDType to use abort_on_failure in intrinsic :type constraint
* fixed EmailAddressType to use abort_on_failure in intrinsic :type constraint
* fixed HostnameType to use abort_on_failure in intrinsic :type constraint
* fixed URIType to use abort_on_failure in intrinsic :type …

Fix identifier types and network types now abort_on_failure for type

---

README.md
docs/README.md
docs/SECURITY.md
docs/experiments/domainic-type-alpha-3/CHANGELOG.md
domainic-attributer/README.md
domainic-type/README.md
domainic-type/docs/USAGE.md
domainic-type/domainic-type.gemspec

Create complete documentation for the Domainic::Type gem while standardizing documentation across the project:
* Add comprehensive README for Domainic::Type with:
* Clear description and use cases
* Quick start with practical examples
* Installation and usage instructions
* Create detailed USAGE.md guide covering:
* Core concepts and features
* Complete type reference
* Integration patterns and examples
Additional documentation improvements:
* Standardize README structure across gems
* Update contributing and documentation links to use wiki URLs
* Add missing docs badge to Domainic::Type README
* Include docs directory in gemspec file list
* Fix license file references
These changes establish Domainic::Type's documentation while bringing consistency to how we present and organize …

Add comprehensive documentation for Domainic::Type

---

docs/experiments/domainic-type-alpha-3/CHANGELOG.md
domainic-type/lib/domainic/type/accessors.rb
domainic-type/lib/domainic/type/config/registry.yml
domainic-type/lib/domainic/type/definitions.rb
domainic-type/lib/domainic/type/types/core/complex_type.rb
domainic-type/lib/domainic/type/types/core/range_type.rb
domainic-type/lib/domainic/type/types/core/rational_type.rb
domainic-type/lib/domainic/type/types/core_extended/big_decimal_type.rb
domainic-type/lib/domainic/type/types/core_extended/set_type.rb
domainic-type/sig/domainic/type/accessors.rbs
domainic-type/sig/domainic/type/definitions.rbs
domainic-type/sig/domainic/type/types/core/complex_type.rbs
domainic-type/sig/domainic/type/types/core/range_type.rbs
domainic-type/sig/domainic/type/types/core/rational_type.rbs
domainic-type/sig/domainic/type/types/core_extended/big_decimal_type.rbs
domainic-type/sig/domainic/type/types/core_extended/set_type.rbs
domainic-type/spec/domainic/type/big_decimal_type_spec.rb
domainic-type/spec/domainic/type/complex_type_spec.rb
domainic-type/spec/domainic/type/definitions_spec.rb
domainic-type/spec/domainic/type/range_type_spec.rb
domainic-type/spec/domainic/type/rational_type_spec.rb
domainic-type/spec/domainic/type/set_type_spec.rb

This introduces type definitions for `BigDecimal`, `Complex`, `Range`, `Rational`, and `Set`, providing flexible validation for these specialized data types. These types are seamlessly integrated into `Domainic::Type::Definitions`, allowing for robust and extensible constraint handling. Each type is also supported by optional validation methods for nilable values.
* `_BigDecimal`: Creates a `BigDecimalType` for validating `BigDecimal` objects.
* `_Complex`: Creates a `ComplexType` for validating `Complex` numbers.
* `_Range`: Creates a `RangeType` for validating `Range` objects.
* `_Rational`: Creates a `RationalType` for validating `Rational` numbers.
* `_Set`: Creates a `SetType` for validating `Set` objects.
* `_BigDecimal?`: Optional validation for `BigDecimal`.
* `_Complex?`: …

Add various core types

---

docs/experiments/domainic-type-alpha-3/CHANGELOG.md
domainic-type/lib/domainic/type/constraint/constraints/nor_constraint.rb
domainic-type/spec/domainic/type/constraint/nor_constraint_spec.rb

Updated the `NorConstraint` to prepend "not" to the short description when a single constraint is applied, clarifying error messages for negated validations.
This addresses a bug where the error message for constraints like `not_matching` was ambiguous and suggested the opposite behavior.
Changes include:
* Updated `NorConstraint#short_description` to prepend "not" for single constraints.
* Adjusted specs to reflect the new behavior for single constraints.
Changelog:
* fixed `Domainic::Type::Constraint::NorConstraint#short_description` to prepend "not" for single constraints.
fixes #163

Fix `Domainic::Type::NorConstraint`

---

docs/experiments/domainic-type-alpha-3/CHANGELOG.md
domainic-type/lib/domainic/type/behavior.rb
domainic-type/lib/domainic/type/config/registry.yml
domainic-type/lib/domainic/type/constraint/constraints/predicate_constraint.rb
domainic-type/sig/domainic/type/behavior.rbs
domainic-type/sig/domainic/type/constraint/constraints/predicate_constraint.rbs
domainic-type/spec/domainic/type/behavior_spec.rb
domainic-type/spec/domainic/type/constraint/predicate_constraint_spec.rb

This introduces a new custom validation mechanism through two key components:
1. A `PredicateConstraint` class that enables custom validation using Procs
2. A `satisfies` method on `Type::Behavior` that provides a natural API for using these custom validations
This addition gives users an escape hatch for complex validation scenarios that aren't covered by the built-in constraints, while maintaining the type system's ergonomics and error handling.
* Added `PredicateConstraint` class for custom Proc-based validation
* Added `satisfies` method to `Type::Behavior` for ergonomic predicate constraints
* Added comprehensive specs for both components
* Added RBS type signatures
* Updated constraint registry to include PredicateConstraint
Example usage:
```ruby
_Integer.satisfies(->(x) { x.prime? …
```

Add `Domainic::Type::Constraint::PredicateConstraint` and satisfies method

---

domainic-dev/.gitignore
domainic-dev/.yardopts
domainic-dev/domainic-dev.gemspec
domainic-dev/lib/domainic/dev/generator/gem_generator.rb
domainic-dev/lib/domainic/dev/generator/templates/gem/.gitignore
domainic-dev/lib/domainic/dev/generator/templates/gem/.yardopts.erb
domainic-dev/lib/domainic/dev/generator/templates/gem/gemspec.erb
domainic-dev/sig/domainic/dev/generator/gem_generator.rbs
domainic-type/.gitignore
domainic-type/.yardopts
domainic-type/domainic-type.gemspec

Update GemGenerator to create .gitignore and .yardopts files for new gems, ensuring consistent configuration across the project. Also updates the gemspec template to include documentation_uri and properly package documentation files.
Related gemspecs updated to match the new structure for consistency.

Enhance GemGenerator to create additional configuration files

---

domainic-attributer/CHANGELOG.md
domainic-attributer/lib/domainic/attributer/attribute/mixin/belongs_to_attribute.rb
domainic-attributer/spec/domainic/attributer/attribute/callback_spec.rb
domainic-attributer/spec/domainic/attributer/attribute/coercer_spec.rb
domainic-attributer/spec/domainic/attributer/attribute/signature_spec.rb
domainic-attributer/spec/domainic/attributer/attribute/validator_spec.rb

Removes special case handling of RSpec test doubles in the BelongsToAttribute#validate_attribute! method, eliminating an implicit dependency on RSpec. Updates related specs to properly stub the is_a? check instead.
This change improves the separation between production and test code by removing test framework specific code from the core library.
Changelog:
* removed RSpec::Mocks::TestDouble check from `Domainic::Attributer::Attribute::BelongsToAttribute#validate_attribute!`

Remove implicit RSpec dependency from `BelongsToAttribute`

---

docs/experiments/domainic-type-alpha-3/CHANGELOG.md
domainic-type/lib/domainic/type/behavior/date_time_behavior.rb
domainic-type/spec/domainic/type/behavior/date_time_behavior_spec.rb

Fixes an issue where the TO_DATETIME_COERCER would incorrectly parse dates by validating pattern matches using a reversible format check. This ensures the parsed date maintains the values from the original string.
The bug was particularly visible at the end of months where the day number could be misinterpreted as a year when using the wrong date pattern (e.g.,"29-12-2024" being parsed as year 29, month 12, day 20).
Changelog:
* fixed `Domainic::Type::Behavior::DateTimeBehavio::TO_DATETIME_COERCER` now validates pattern matches by comparing the reformatted result against the original input

Fix date parsing ambiguity in DateTimeBehavior

---

docs/milestones/domainic-command-v0.2.0.md
domainic-dev/lib/domainic/dev/generator/gem_generator.rb
domainic-dev/lib/domainic/dev/generator/templates/gem/gemspec.erb

Update gem generator templates to fix interpolation and naming issues:
* Fix documentation_uri in gemspec.erb to properly interpolate version
* Fix "Could not find ".yardopts" in any of your source paths." error
Changelog:
* changed `Generator::GemGenerator#create_yardopts`
* fixed gemspec.erb template
* updated milestone formatting in docs/milestones/domainic-command-v0.2.0.md

Fix gem generator templates and milestone formatting

---

docs/SECURITY.md
docs/projects/domainic-v0.1.0/README.md
docs/projects/domainic-v0.1.0/updates/2025-01-01-01.md
domainic-attributer/CHANGELOG.md
domainic-attributer/docs/USAGE.md
domainic-attributer/lib/domainic/attributer/attribute/callback.rb
domainic-attributer/sig/domainic/attributer/attribute/callback.rbs

This releases domainic-attributer v0.2.0
Key Changes in v0.2.0:
* New specialized error classes for validation, callback, and coercion failures
* Improved nil value handling in coercion
* Removed implicit RSpec dependency
* Various bug fixes and documentation improvements

Release domainic-attributer v0.2.0

---

domainic-command/docs/USAGE.md

This PR addresses the issue of unclear or incorrect behavior when attempting to add custom error messages to a `Domainic::Command` class. The documentation and behavior for adding custom errors (e.g., `add_error`) was updated to clarify usage and improve error-handling logic.
Fixes #183
- Updated documentation examples in `USAGE.md` to correctly demonstrate how to use `add_error`.
- Fixed logic for adding custom errors when command arguments (e.g., `age`) fail validation.
- Verified the corrected examples work as expected via manual testing.
**Manual Testing Performed**  
1. Defined the following command:
```ruby
class CreateUser
include Domainic::Command
argument :email, String, required: true
argument :password, String, required: true
argument …
```

Update the example in USAGE.md to use the correct method name

---

.github/actions/test/ruby/action.yml

This fixes an error where the Test action would fail for external collaborators because github actions will not pass secrets to the runner unless the pull request author is a member of the Domainic organization.
* see #192 
* see #193 
* see [build #263](https://github.com/domainic/domainic/actions/runs/12579657433)
* see [build #264](https://github.com/domainic/domainic/actions/runs/12579763662)
* Updated the test/ruby action to not report coverage for external collaborators. This will cause the test action to stop raising errors for the missing codacy token as a side effect.

Fix codacy error for external collaborators

---

domainic-command/docs/USAGE.md
domainic-command/lib/domainic/command/result.rb
domainic-command/sig/domainic/command/result.rbs
domainic-command/spec/domainic/command/result_spec.rb

This PR adds the and_then method to the Domainic::Command::Result class, enabling a functional and chainable approach to handling command results. This simplifies the process of chaining commands and reduces boilerplate code for error handling.
Fixes #176
**Implementation Details**
- The and_then method ensures a safe and predictable flow of command chaining.
- If the block does not return a Result, the chain is terminated with the original result.
**Functional Validation**
The following example was tested successfully in irb:
```rb
result = Domainic::Command::Result.success(value: 42)
chained_result = result
.and_then { |r| Domainic::Command::Result.success(value: r.value * 2) }
.and_then { |r| Domainic::Command::Result.success(value: r.value + …
```

Domainic command/feature/add and then method

---

domainic-command/domainic-command.gemspec

This ensures docs/USAGE.md is included with the distributed gem.
* fixes #173
* added docs to the gemspec files

Fix docs/USAGE.md not included in gem package
