README.md
domainic-attributer/CHANGELOG.md
domainic-attributer/README.md
domainic-attributer/lib/domainic/attributer/attribute/callback.rb
domainic-attributer/lib/domainic/attributer/attribute/coercer.rb
domainic-attributer/lib/domainic/attributer/attribute/validator.rb
domainic-attributer/lib/domainic/attributer/errors/aggregate_error.rb
domainic-attributer/lib/domainic/attributer/errors/callback_execution_error.rb
domainic-attributer/lib/domainic/attributer/errors/coercion_execution_error.rb
domainic-attributer/lib/domainic/attributer/errors/error.rb
domainic-attributer/lib/domainic/attributer/errors/validation_execution_error.rb
domainic-attributer/sig/domainic/attributer/attribute/callback.rbs
domainic-attributer/sig/domainic/attributer/attribute/coercer.rbs
domainic-attributer/sig/domainic/attributer/attribute/validator.rbs
domainic-attributer/sig/domainic/attributer/errors/aggregate_error.rbs
domainic-attributer/sig/domainic/attributer/errors/callback_execution_error.rbs
domainic-attributer/sig/domainic/attributer/errors/coercion_execution_error.rbs
domainic-attributer/sig/domainic/attributer/errors/error.rbs
domainic-attributer/sig/domainic/attributer/errors/validation_execution_error.rbs
domainic-attributer/spec/domainic/attributer/aggregate_error_spec.rb
domainic-attributer/spec/domainic/attributer/attribute/callback_spec.rb
domainic-attributer/spec/domainic/attributer/attribute/coercer_spec.rb
domainic-attributer/spec/domainic/attributer/attribute/validator_spec.rb

This includes several related changes to improve error handling and documentation in Domainic::Attributer:
- Added specialized error classes (ValidationExecutionError, CallbackExecutionError, and CoercionExecutionError)
- Updated callback and validation behavior to collect and aggregate errors
- Refined coercion error handling and reporting
- Added new Error Handling section to README explaining error behavior
- Fixed misleading examples around nil handling in validators
- Updated Domainic README to clarify pre-release status
* resolves #8 
* resolves #19 
* resolves #20

Update documentation and introduce execution error types

---

domainic-type/lib/domainic/type/constraint/constraints/all_constraint.rb
domainic-type/lib/domainic/type/constraint/constraints/and_constraint.rb
domainic-type/lib/domainic/type/constraint/constraints/any_constraint.rb
domainic-type/lib/domainic/type/constraint/constraints/not_constraint.rb
domainic-type/lib/domainic/type/constraint/constraints/or_constraint.rb
domainic-type/sig/domainic/type/constraint/constraints/all_constraint.rbs
domainic-type/sig/domainic/type/constraint/constraints/and_constraint.rbs
domainic-type/sig/domainic/type/constraint/constraints/any_constraint.rbs
domainic-type/sig/domainic/type/constraint/constraints/not_constraint.rbs
domainic-type/sig/domainic/type/constraint/constraints/or_constraint.rbs
domainic-type/spec/domainic/type/constraint/all_constraint_spec.rb
domainic-type/spec/domainic/type/constraint/and_constraint_spec.rb
domainic-type/spec/domainic/type/constraint/any_constraint_spec.rb
domainic-type/spec/domainic/type/constraint/not_constraint_spec.rb
domainic-type/spec/domainic/type/constraint/or_constraint_spec.rb

Adds five fundamental logical constraints to the type system:
- `AllConstraint`: Validates that every element in an enumerable satisfies a given constraint
- `AnyConstraint`: Validates that at least one element in an enumerable satisfies a given constraint
- `AndConstraint`: Validates that a value satisfies all of a set of constraints
- `OrConstraint`: Validates that a value satisfies at least one of a set of constraints
- `NotConstraint`: Inverts another constraint's validation logic
These constraints enable more complex type validations:
```ruby
class ArrayType
include Domainic::Type::Behavior
def of(type)
sub = Constraint::Resolver.resolve!(:type).new(:self, type)
constrain :entries, :all, 'having elements of', sub
end
end
class ArrayType
include Domainic::Type::Behavior
def …
```

Add various `Domainic::Type` logic constraints

---

domainic-type/lib/domainic/type/types/void_type.rb
domainic-type/sig/domainic/type/types/void_type.rbs
domainic-type/spec/domainic/type/void_type_spec.rb

Add `Domainic::Type::VoidType`

---

.codacy.yml
Gemfile.lock
README.md
domainic-attributer/README.md
domainic-dev/README.md
domainic-dev/domainic-dev.gemspec
domainic-type/README.md
domainic.gemspec

Update documentation and configuration with clearer organization and more robust dependency specifications:
* Completely reorganized domainic-dev README.md for better clarity and usability, including quick start guide and practical workflows
* Made minor formatting and clarity improvements to other README files
* Updated all bundler dependencies to use the more precise ~> operator
* Added Codacy configuration file for consistent code quality checks

Improve documentation and dependency management

---

domainic-type/lib/domainic/type/behavior/enumerable_behavior.rb
domainic-type/lib/domainic/type/config/registry.yml
domainic-type/lib/domainic/type/types/core/array_type.rb
domainic-type/lib/domainic/type/types/core/hash_type.rb
domainic-type/sig/domainic/type/types/core/array_type.rbs
domainic-type/sig/domainic/type/types/core/hash_type.rbs
domainic-type/spec/domainic/type/array_type_spec.rb
domainic-type/spec/domainic/type/behavior/enumerable_behavior_spec.rb
domainic-type/spec/domainic/type/hash_type_spec.rb

After several iterations, this commit marks the completion of our enumerable validation system, introducing a powerful Hash type implementation alongside comprehensive specs for all enumerable-related components.
The Hash type brings robust validation capabilities including:
* Key/value type validation
* Key/value presence constraints
* Key/value exclusion rules
* Full enumerable behavior support
This addition rounds out our enumerable validation suite, which now includes:
* Rich enumerable behavior module with extensive validation methods
* Array type with complete enumerable support
* Hash type with specialized key/value validation
* Comprehensive test coverage across all components
The enumerable validation system now provides a consistent, intuitive interface across different …

Complete Hash implementation and enumerable validation suite

---

.github/labeler.yml
.github/workflows/publish_wiki.yml
.github/workflows/pull_request_labeler.yml
docs/README.md
docs/milestones/README.md
docs/projects/README.md
domainic-dev/lib/domainic/dev/generator/milestone_doc_generator.rb
domainic-dev/lib/domainic/dev/generator/project_doc_generator.rb
domainic-dev/lib/domainic/dev/generator/project_update_doc_generator.rb
domainic-dev/sig/domainic/dev/generator/milestone_doc_generator.rbs
domainic-dev/sig/domainic/dev/generator/project_doc_generator.rbs
domainic-dev/sig/domainic/dev/generator/project_update_doc_generator.rbs

This PR introduces documentation management tooling and PR automation workflows to streamline our development process and ensure consistent documentation practices across the project.
* Set up documentation structure with dedicated READMEs for main docs, projects, and milestones
* Added GitHub Action to automatically sync docs/ directory with GitHub wiki
* Enhanced milestone documentation generator to automatically update milestones/README.md
* Added project document generation improvements with user instructions
* Implemented PR labeler workflow with configuration for all gems
* Added PR template with standardized checklist
The documentation sync workflow is configured to run only when changes are made to the docs/ directory and includes …

Add documentation tooling and PR management workflows

---

.rubocop-base.yml
domainic-type/lib/domainic/type/behavior/numeric_behavior.rb
domainic-type/lib/domainic/type/config/registry.yml
domainic-type/lib/domainic/type/constraint/constraints/polarity_constraint.rb
domainic-type/lib/domainic/type/types/core/float_type.rb
domainic-type/lib/domainic/type/types/core/integer_type.rb
domainic-type/sig/domainic/type/behavior/numeric_behavior.rbs
domainic-type/sig/domainic/type/types/core/float_type.rbs
domainic-type/sig/domainic/type/types/core/integer_type.rbs
domainic-type/spec/domainic/type/behavior/numeric_behavior_spec.rb
domainic-type/spec/domainic/type/float_type_spec.rb
domainic-type/spec/domainic/type/integer_type_spec.rb

This introduces a comprehensive set of numeric-related types and constraints, including:
* Core numeric behavior module (`NumericBehavior`)
* Fundamental numeric constraints (Divisibility, Finiteness, Polarity, Parity)
* Basic numeric types (`IntegerType`, `FloatType`)
* resolves #46
* resolves #51  
* resolves #52  
* resolves #53
* Added numeric constraints:
* `DivisibilityConstraint` for checking if numbers are evenly divisible
* `FinitenessConstraint` for validating finite/infinite numbers
* `PolarityConstraint` for checking numeric signs
* `ParityConstraint` for even/odd validation
* Added numeric behavior and types:
* `NumericBehavior` module providing comprehensive numeric validations
* `IntegerType` for integer validation
* `FloatType` for floating-point validation
* …

Add Numeric Related Types & Constraints

---

domainic-type/lib/domainic/type/accessors.rb
domainic-type/lib/domainic/type/behavior/string_behavior.rb
domainic-type/lib/domainic/type/config/registry.yml
domainic-type/lib/domainic/type/constraint/constraints/case_constraint.rb
domainic-type/lib/domainic/type/constraint/constraints/character_set_constraint.rb
domainic-type/lib/domainic/type/constraint/constraints/match_pattern_constraint.rb
domainic-type/lib/domainic/type/types/core/string_type.rb
domainic-type/lib/domainic/type/types/core/symbol_type.rb
domainic-type/sig/domainic/type/accessors.rbs
domainic-type/sig/domainic/type/behavior/string_behavior.rbs
domainic-type/sig/domainic/type/constraint/constraints/case_constraint.rbs
domainic-type/sig/domainic/type/constraint/constraints/character_set_constraint.rbs
domainic-type/sig/domainic/type/constraint/constraints/match_pattern_constraint.rbs
domainic-type/sig/domainic/type/types/core/string_type.rbs
domainic-type/sig/domainic/type/types/core/symbol_type.rbs
domainic-type/spec/domainic/type/behavior/string_behavior_spec.rb
domainic-type/spec/domainic/type/constraint/case_constraint_spec.rb
domainic-type/spec/domainic/type/constraint/character_set_constraint_spec.rb
domainic-type/spec/domainic/type/constraint/match_pattern_constraint_spec.rb
domainic-type/spec/domainic/type/string_type_spec.rb
domainic-type/spec/domainic/type/symbol_type_spec.rb

This PR adds comprehensive string validation functionality to the Type system, including new constraints, behaviors, and core types for strings and symbols. The changes provide a rich set of tools for validating string content, formatting, and structure in domain models.
* resolves #62
* resolves #84
* resolves #85
* resolves #86
* resolves #87
* resolves #88
* Added `MatchPatternConstraint` for regex-based string validation
* Added `CaseConstraint` for string case format validation (upper, lower, mixed, title)
* Added `CharacterSetConstraint` for character set validation (ASCII, alphanumeric, etc.)
* Added `StringBehavior` module providing comprehensive string validation capabilities
* Added `StringType` for string validation using behavior composition
* Added `SymbolType` for symbol …

Add String validation functionality to Type system

---

Gemfile.lock
docs/experiments/domainic-type-alpha-3/CHANGELOG.md
docs/experiments/domainic-type-alpha-3/EXAMPLES.md
docs/experiments/domainic-type-alpha-3/KNOWN_ISSUES.md
domainic-type/domainic-type.gemspec
rbs_collection.lock.yaml

* [#138](https://github.com/domainic/domainic/issues/138) error messages only show failed constraints.

Release domainic-type v0.1.0-alpha.3.0.1

---

docs/milestones/README.md
docs/milestones/domainic-attributer-v0.3.0.md
domainic-dev/lib/domainic/dev/generator/milestone_doc_generator.rb

Detailed milestone document outlining the planned changes, enhancements, and breaking changes for the upcoming domainic-attributer v0.3.0 release.
Key aspects covered in the milestone document:
* Custom validation error messages with improved formatting
* Introduction of immutable attributes
* Feature toggles for initialization and validation
* Default attribute configuration at global and class levels
* Enhanced error backtraces pointing to user code
The document also includes:
* Release goals and acceptance criteria
* Breaking change details and migration considerations
* Release preparation workflow
* Potential risks and mitigations
* Open questions for further discussion
This documentation serves as a comprehensive guide for the v0.3.0 release, providing a clear roadmap of the planned …

Add milestone documentation for domainic-attributer v0.3.0

---

README.md
docs/CONTRIBUTING.md
docs/README.md
docs/SECURITY.md
docs/experiments/README.md
docs/experiments/domainic-type-alpha-3/CHANGELOG.md
docs/experiments/domainic-type-alpha-3/EXAMPLES.md
docs/experiments/domainic-type-alpha-3/KNOWN_ISSUES.md
docs/experiments/domainic-type-alpha-3/README.md
docs/experiments/domainic-type-alpha-3/TROUBLESHOOTING.md
docs/milestones/domainic-attributer-v0.1.0.md
docs/milestones/domainic-attributer-v0.2.0.md
docs/milestones/domainic-attributer-v0.3.0.md
docs/milestones/domainic-boundary-v0.1.0.md
docs/milestones/domainic-command-v0.1.0.md
docs/milestones/domainic-type-v0.1.0.md
docs/projects/README.md
docs/projects/domainic-v0.1.0/README.md
docs/projects/domainic-v0.1.0/updates/2024-12-12-01.md
docs/projects/domainic-v0.1.0/updates/2024-12-23-01.md
domainic-dev/lib/domainic/dev/generator/milestone_doc_generator.rb
domainic-dev/lib/domainic/dev/generator/project_doc_generator.rb
domainic-dev/lib/domainic/dev/generator/templates/milestone_doc/milestone.md.erb
domainic-dev/lib/domainic/dev/generator/templates/project_doc/README.md.erb
domainic-dev/sig/domainic/dev/generator/milestone_doc_generator.rbs
domainic-dev/sig/domainic/dev/generator/project_doc_generator.rbs

This introduces a comprehensive update to our documentation system, focusing on improved organization, consistency, and automated generation. The changes span both our static documentation and our documentation generation tools.
* Streamlined docs/README.md as a central documentation portal
* Improved navigation between different documentation sections
* Fixed list indentation and formatting issues
* Standardized status indicators and badges across all docs
* Converted custom notes to GitHub-style alerts
* Updated ProjectDocGenerator with:
* Configurable status badges
* Start/due date tracking
* Task tracking badges
* Project health indicators
* Proper URI encoding for badge parameters
* Enhanced MilestoneDocGenerator with:
* Matching badge format and style
* Improved date handling
* Task …

Documentation improvements and generator updates

---

docs/experiments/domainic-type-alpha-3/CHANGELOG.md
docs/experiments/domainic-type-alpha-3/EXAMPLES.md
domainic-type/lib/domainic/type/config/registry.yml
domainic-type/lib/domainic/type/constraint/constraints/attribute_presence_constraint.rb
domainic-type/lib/domainic/type/constraint/constraints/instance_of_constraint.rb
domainic-type/lib/domainic/type/definitions.rb
domainic-type/lib/domainic/type/types/specialized/instance_type.rb
domainic-type/sig/domainic/type/constraint/constraints/attribute_presence_constraint.rbs
domainic-type/sig/domainic/type/constraint/constraints/instance_of_constraint.rbs
domainic-type/sig/domainic/type/definitions.rbs
domainic-type/sig/domainic/type/types/specialized/instance_type.rbs
domainic-type/spec/domainic/type/constraint/attribute_presence_constraint_spec.rb
domainic-type/spec/domainic/type/constraint/instance_of_constraint_spec.rb
domainic-type/spec/domainic/type/definitions_spec.rb
domainic-type/spec/domainic/type/instance_type_spec.rb
rbs_collection.lock.yaml

This introduces the `Domainic::Type::InstanceType` class and associated constraints, providing powerful capabilities for validating objects against specific classes, modules, and attribute structures. The new features enable precise type-checking and ensure conformance to expected object structures within the Domainic::Type system.
Key changes:
* Added `Domainic::Type::InstanceType` for constraining objects to specific classes or modules and validating attributes
* Introduced `Domainic::Type::Definitions._Instance` and `_Instance?` methods for creating `InstanceType` and `Nilable` constraints
* Added `Domainic::Type::Constraint::InstanceOfConstraint` to validate that a value is an instance of a specific class or module
* Added `Domainic::Type::Constraint::AttributePresenceConstraint` to …

Add `Domainic::Type::InstanceType`

---

domainic-type/lib/domainic/type/behavior/string_behavior.rb
domainic-type/lib/domainic/type/behavior/string_behavior/matching_behavior.rb
domainic-type/lib/domainic/type/behavior/uri_behavior.rb
domainic-type/lib/domainic/type/config/registry.yml
domainic-type/lib/domainic/type/definitions.rb
domainic-type/lib/domainic/type/types/network/email_address_type.rb
domainic-type/lib/domainic/type/types/network/hostname_type.rb
domainic-type/lib/domainic/type/types/network/uri_type.rb
domainic-type/sig/domainic/type/behavior/string_behavior.rbs
domainic-type/sig/domainic/type/behavior/string_behavior/matching_behavior.rbs
domainic-type/sig/domainic/type/behavior/uri_behavior.rbs
domainic-type/sig/domainic/type/definitions.rbs
domainic-type/sig/domainic/type/types/network/email_address_type.rbs
domainic-type/sig/domainic/type/types/network/hostname_type.rbs
domainic-type/sig/domainic/type/types/network/uri_type.rbs
domainic-type/spec/domainic/type/behavior/string_behavior/matching_behavior_spec.rb
domainic-type/spec/domainic/type/behavior/string_behavior_spec.rb
domainic-type/spec/domainic/type/behavior/uri_behavior_spec.rb
domainic-type/spec/domainic/type/definitions_spec.rb
domainic-type/spec/domainic/type/email_address_type_spec.rb
domainic-type/spec/domainic/type/hostname_type_spec.rb
domainic-type/spec/domainic/type/uri_type_spec.rb

This introduces several new networking types to enhance Domainic's ability to validate URIs, hostnames, and email addresses. These include:
* `Domainic::Type::URIType` for validating URIs according to RFC 3986 standards.
* `Domainic::Type::HostnameType` for validating hostnames according to RFC 1034 and RFC 1123. 
* `Domainic::Type::EmailAddressType` for validating email addresses according to RFC 5321/5322.
It also refactors string matching logic into a dedicated `MatchingBehavior` module and extracts top-level domain validation into a reusable `URIBehavior` module.
* Added `Domainic::Type::URIType` for validating URIs with support for scheme, host, path and query constraints.
* Added `_Uri` and `_Uri?` methods to `Domainic::Type::Definitions` for creating URI type constraints.
* Added …

Add Basic Network Types

---

docs/experiments/domainic-type-alpha-3/CHANGELOG.md
domainic-type/lib/domainic/type/behavior/date_time_behavior.rb
domainic-type/lib/domainic/type/behavior/sizable_behavior.rb
domainic-type/lib/domainic/type/config/registry.yml
domainic-type/lib/domainic/type/constraint/constraints/range_constraint.rb
domainic-type/lib/domainic/type/definitions.rb
domainic-type/lib/domainic/type/types/datetime/date_time_type.rb
domainic-type/lib/domainic/type/types/datetime/date_type.rb
domainic-type/lib/domainic/type/types/datetime/time_type.rb
domainic-type/sig/domainic/type/behavior/date_time_behavior.rbs
domainic-type/sig/domainic/type/behavior/sizable_behavior.rbs
domainic-type/sig/domainic/type/constraint/constraints/range_constraint.rbs
domainic-type/sig/domainic/type/definitions.rbs
domainic-type/sig/domainic/type/types/datetime/date_time_type.rbs
domainic-type/sig/domainic/type/types/datetime/date_type.rbs
domainic-type/sig/domainic/type/types/datetime/time_type.rbs
domainic-type/spec/domainic/type/behavior/date_time_behavior_spec.rb
domainic-type/spec/domainic/type/constraint/range_constraint_spec.rb
domainic-type/spec/domainic/type/date_time_type_spec.rb
domainic-type/spec/domainic/type/date_type_spec.rb
domainic-type/spec/domainic/type/definitions_spec.rb
domainic-type/spec/domainic/type/time_type_spec.rb
domainic-type/spec/spec_helper.rb
domainic-type/spec/support/shared_examples/a_date_time_type.rb

This introduces three new DateTime-related types (DateType, DateTimeType, TimeType) and enhances the RangeConstraint to support validation for all comparable types, not just numeric values. These changes aim to provide robust and flexible validation capabilities for dates, times, and ranges in Domainic.
* DateType
* Validates Date objects.
* Includes DateTimeBehavior for natural language date constraints (e.g., being_on_or_after).
* DateTimeType
* Validates DateTime objects.
* Extends with DateTimeBehavior for full-featured date and time validation.
* TimeType
* Validates Time objects.
* Integrates DateTimeBehavior for flexible time-based constraints.
* Generalized to validate all comparable types (e.g., Date, Time, custom objects).
* Updated to:
* Use logical operators (<, <=, >, >=) for …

Add DateType, DateTimeType, and TimeType with Definitions

---

Gemfile.lock
docs/README.md
docs/SECURITY.md
docs/experiments/domainic-type-alpha-3/CHANGELOG.md
docs/experiments/domainic-type-alpha-3/EXAMPLES.md
docs/experiments/domainic-type-alpha-3/KNOWN_ISSUES.md
docs/experiments/domainic-type-alpha-3/README.md
docs/experiments/domainic-type-alpha-3/TROUBLESHOOTING.md
domainic-type/domainic-type.gemspec
rbs_collection.lock.yaml

This release continues our experiment with flexible type validation in Ruby! 
We're adding date and time types to help validate date, datetime, and time 
values.
- DateTime types:
- Date - validates Dates
- DateTime - validates DateTimes
- Time - validates Times
The full documentation has been updated at https://github.com/domainic/domainic/tree/domainic-type-v0.1.0-alpha.3.2.0/docs/experiments/domainic-type-alpha-3/EXAMPLES.md
Please try out these new types and let us know how they work for your use cases. Your feedback helps shape the future of domain-driven design in Ruby!

Release domainic-type v0.1.0-alpha.3.2.0

---

docs/experiments/domainic-type-alpha-3/CHANGELOG.md
domainic-type/lib/domainic/type/behavior/date_time_behavior.rb
domainic-type/lib/domainic/type/definitions.rb
domainic-type/lib/domainic/type/types/datetime/date_time_string_type.rb
domainic-type/sig/domainic/type/behavior/date_time_behavior.rbs
domainic-type/sig/domainic/type/definitions.rbs
domainic-type/sig/domainic/type/types/datetime/date_time_string_type.rbs
domainic-type/spec/domainic/type/behavior/date_time_behavior_spec.rb
domainic-type/spec/domainic/type/date_time_string_type_spec.rb
domainic-type/spec/domainic/type/definitions_spec.rb

This PR introduces the `Domainic::Type::DateTimeStringType` for validating datetime strings against various predefined formats and integrates it into `Domainic::Type::Definitions` via the `_DateTimeString` and `_DateTimeString?` methods. Additionally, it enhances `DateTimeBehavior` to provide robust support for parsing and validating datetime strings.
* Validates datetime strings against multiple formats:
* ISO 8601
* RFC2822
* American and European styles
* Supports chronological constraints (e.g., being_after, being_between).
* Integration with `DateTimeBehavior` for range-based validation.
* Flexible, fluent interface for format-specific and temporal constraints.
* Added regex patterns and validation methods for supported formats.
* `_DateTimeString`: Creates a `DateTimeStringType` for …

Add `Domainic::Type::DateTimeStringType` and `_DateTimeString` Definitions

---

docs/experiments/domainic-type-alpha-3/CHANGELOG.md
domainic-type/lib/domainic/type/behavior/date_time_behavior.rb
domainic-type/lib/domainic/type/config/registry.yml
domainic-type/lib/domainic/type/definitions.rb
domainic-type/lib/domainic/type/types/datetime/timestamp_type.rb
domainic-type/sig/domainic/type/behavior/date_time_behavior.rbs
domainic-type/sig/domainic/type/definitions.rbs
domainic-type/sig/domainic/type/types/datetime/timestamp_type.rbs
domainic-type/spec/domainic/type/behavior/date_time_behavior_spec.rb
domainic-type/spec/domainic/type/definitions_spec.rb
domainic-type/spec/domainic/type/timestamp_type_spec.rb

This introduces the `Domainic::Type::TimestampType` for validating Unix timestamps (seconds since the Unix epoch) and integrates it into `Domainic::Type::Definitions` via the `_Timestamp` and `_Timestamp?` methods. Additionally, it enhances `DateTimeBehavior` to support Unix timestamps alongside existing datetime formats.
* Validates Unix timestamps (`Integer` values representing seconds since the epoch).
* Supports both historical and modern timestamps.
* Provides chronological constraints (e.g., being_after, being_between).
* Fluent interface for timestamp-based validation.
* Integration with `DateTimeBehavior` for range and boundary constraints.
* `_Timestamp`: Creates a `TimestampType` for validating Unix timestamps.
* `_Timestamp?`: Creates a nilable `TimestampType` for optional …

Add `Domainic::Type::TimestampType` and `_Timestamp` Definitions

---

Gemfile.lock
docs/README.md
docs/SECURITY.md
docs/experiments/domainic-type-alpha-3/CHANGELOG.md
docs/experiments/domainic-type-alpha-3/EXAMPLES.md
docs/experiments/domainic-type-alpha-3/README.md
domainic-type/docs/USAGE.md
domainic-type/domainic-type.gemspec
rbs_collection.lock.yaml

This releases domainic-type v0.1.0-alpha.3.3.0, adding support for additional Ruby core types and improving documentation coverage.
Added support for the following Ruby core types:
- BigDecimal - Type-safe validation for arbitrary-precision decimals
- Complex - Validation for complex numbers 
- DateTimeString - Flexible datetime string format validation
- Range - Type-safe Range object validation
- Rational - Precise rational number validation
- Set - Collection validation for Set objects
- Timestamp - Unix timestamp validation
- Added comprehensive usage examples for all new types in EXAMPLES.md
- Added type documentation in USAGE.md
- Updated type list in README.md
- Updated all documentation links to reference new version
- Updated version to 0.1.0-alpha.3.3.0 in all relevant files
- …

Release domainic-type v0.1.0-alpha.3.3.0

---

domainic-attributer/.gitignore
domainic-attributer/.yardopts
domainic-attributer/README.md
domainic-attributer/domainic-attributer.gemspec
domainic-attributer/lib/domainic/attributer.rb
domainic-attributer/lib/domainic/attributer/class_methods.rb
domainic-attributer/lib/domainic/attributer/dsl/attribute_builder.rb
domainic-attributer/lib/domainic/attributer/dsl/attribute_builder/option_parser.rb
domainic-attributer/sig/domainic/attributer.rbs
domainic-attributer/sig/domainic/attributer/class_methods.rbs
domainic-attributer/sig/domainic/attributer/dsl/attribute_builder.rbs
domainic-attributer/sig/domainic/attributer/dsl/attribute_builder/option_parser.rbs

Significantly improves documentation quality and consistency throughout the codebase with a focus on public-facing APIs and developer experience.
Changes include:
* Expanded and clarified module/class level documentation with better examples
* Added comprehensive method documentation with detailed examples and edge cases
* Improved YARD documentation formatting and consistency
* Updated README with clearer value propositions and use cases
* Enhanced .yardopts configuration for better documentation generation
* Made documentation more accessible by improving example clarity
Documentation improvements focus on:
* DSL::AttributeBuilder methods (coerce_with, validate_with, etc.)
* Visibility control methods (public, private, protected)
* Core class and module descriptions
* Attribute …

Enhance documentation for `Domainic::Attributer`

---

README.md
docs/README.md
docs/SECURITY.md
docs/milestones/domainic-command-v0.1.0.md
docs/projects/README.md
docs/projects/domainic-v0.1.0/README.md
docs/projects/domainic-v0.1.0/updates/2024-12-29-01.md
domainic-command/CHANGELOG.md

Initial release of Domainic::Command, providing a robust implementation of the Command pattern for Ruby applications. This release includes core functionality for type-safe business operations with standardized error handling and composable workflows.
Key features:
* Type-safe input/output validation
* Thread-safe context management
* Unix-compatible status codes
* Comprehensive error handling
* Integration with Domainic::Type

Release domainic-command v0.1.0

---

docs/milestones/README.md
docs/milestones/domainic-command-v0.2.0.md
domainic-command/spec/domainic/command/context/attribute_set_spec.rb

This addresses various spec failures and adds documentation for the domainic-command v0.2.0 milestone

Fix various spec errors and documentation enhancements

---

.github/COMMIT_MESSAGE_TEMPLATE.md
Gemfile.lock
docs/README.md
docs/SECURITY.md
docs/experiments/domainic-type-alpha-3/CHANGELOG.md
docs/experiments/domainic-type-alpha-3/EXAMPLES.md
domainic-type/docs/USAGE.md
domainic-type/domainic-type.gemspec
rbs_collection.lock.yaml

This PR prepares the v0.1.0-alpha.3.4.0 release of domainic-type. This release adds custom constraints through the new satisfies method which enables validation rules beyond what built-in constraints can provide.
Key Changes:
* Added custom constraint support via satisfies method available to all types
* Fixed NorConstraint description to properly show negation
* Fixed date parsing ambiguity in DateTimeBehavior
* Updated documentation with examples of custom constraints
Release Tasks:
Once merged, we'll create the release and tag on GitHub.

Release domainic-type v0.1.0-alpha.3.4.0
